#!/usr/bin/env python3
"""
邮件模板系统
"""

def get_inquiry_notification_email(inquiry_data):
    """生成询盘通知邮件内容"""
    
    # 管理员通知邮件
    admin_subject = f"New Inquiry from {inquiry_data.get('name', 'Unknown')} - {inquiry_data.get('inquiry_type', 'General').title()}"
    
    admin_body = f"""
New inquiry received from the website:

CONTACT INFORMATION:
- Name: {inquiry_data.get('name', 'N/A')}
- Email: {inquiry_data.get('email', 'N/A')}
- Company: {inquiry_data.get('company', 'N/A')}
- Phone: {inquiry_data.get('phone', 'N/A')}
- Country: {inquiry_data.get('country', 'N/A')}

INQUIRY DETAILS:
- Type: {inquiry_data.get('inquiry_type', 'General').title()}
- Product Interest: {inquiry_data.get('product_interest', 'N/A')}
- Screen Size: {inquiry_data.get('screen_size', 'N/A')}
- Budget Range: {inquiry_data.get('budget_range', 'N/A')}

MESSAGE:
{inquiry_data.get('message', 'No message provided')}

ADDITIONAL INFO:
- Newsletter Subscription: {'Yes' if inquiry_data.get('newsletter') == '1' else 'No'}
- Language: {inquiry_data.get('language', 'en').upper()}
- Source: {inquiry_data.get('source', 'website').title()}
- Timestamp: {inquiry_data.get('timestamp', 'N/A')}

Please respond to this inquiry within 24 hours.

---
This email was automatically generated by the LED website contact form.
    """.strip()
    
    # 客户确认邮件
    customer_subject = "Thank you for your inquiry - Shenzhen Lianjin Optoelectronics"
    
    customer_body = f"""
Dear {inquiry_data.get('name', 'Valued Customer')},

Thank you for your interest in our LED display solutions!

We have received your inquiry regarding {inquiry_data.get('product_interest', 'our LED products')} and our team will review your requirements carefully.

INQUIRY SUMMARY:
- Inquiry Type: {inquiry_data.get('inquiry_type', 'General').title()}
- Product Interest: {inquiry_data.get('product_interest', 'General LED Solutions')}
- Your Message: {inquiry_data.get('message', '')[:200]}{'...' if len(inquiry_data.get('message', '')) > 200 else ''}

WHAT HAPPENS NEXT:
1. Our technical team will review your requirements
2. We will prepare a customized solution proposal
3. You will receive a detailed response within 24 hours
4. If needed, we will schedule a consultation call

CONTACT INFORMATION:
- Email: sales@lianjin-led.com
- Phone: +86-755-1234-5678
- WhatsApp: +86 123 456 7890

If you have any urgent questions, please don't hesitate to contact us directly.

Best regards,
Sales Team
Shenzhen Lianjin Optoelectronics Co., Ltd.

---
This is an automated confirmation email. Please do not reply to this email.
For any questions, please contact us at sales@lianjin-led.com
    """.strip()
    
    return {
        'admin': {
            'subject': admin_subject,
            'body': admin_body
        },
        'customer': {
            'subject': customer_subject,
            'body': customer_body
        }
    }

def get_inquiry_followup_email(inquiry_data, followup_type='general'):
    """生成询盘跟进邮件模板"""
    
    templates = {
        'quote_sent': {
            'subject': f"Quote for {inquiry_data.get('product_interest', 'LED Display')} - Lianjin Optoelectronics",
            'body': f"""
Dear {inquiry_data.get('name', 'Valued Customer')},

Thank you for your interest in our LED display solutions.

Please find attached our detailed quotation for your {inquiry_data.get('product_interest', 'LED display')} project.

The quote includes:
- Product specifications and pricing
- Installation guidelines
- Warranty information
- Technical support details

This quotation is valid for 30 days. If you have any questions or need modifications, please don't hesitate to contact us.

We look forward to working with you on this project.

Best regards,
Sales Team
Shenzhen Lianjin Optoelectronics Co., Ltd.
            """.strip()
        },
        'technical_response': {
            'subject': f"Technical Information - {inquiry_data.get('product_interest', 'LED Display')}",
            'body': f"""
Dear {inquiry_data.get('name', 'Valued Customer')},

Thank you for your technical inquiry about our {inquiry_data.get('product_interest', 'LED display solutions')}.

Our technical team has prepared detailed information to address your questions:

[Technical details would be inserted here based on the specific inquiry]

If you need additional technical specifications or have further questions, please feel free to contact our technical support team.

Best regards,
Technical Support Team
Shenzhen Lianjin Optoelectronics Co., Ltd.
            """.strip()
        }
    }
    
    return templates.get(followup_type, templates['quote_sent'])

def get_html_email_template(content_data, template_type='inquiry_confirmation'):
    """生成HTML邮件模板"""
    
    # 基础HTML模板
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{content_data.get('subject', 'Lianjin Optoelectronics')}</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
            }}
            .header {{
                background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%);
                color: white;
                padding: 30px 20px;
                text-align: center;
                border-radius: 8px 8px 0 0;
            }}
            .content {{
                background: #ffffff;
                padding: 30px 20px;
                border: 1px solid #e5e7eb;
            }}
            .footer {{
                background: #f9fafb;
                padding: 20px;
                text-align: center;
                font-size: 12px;
                color: #6b7280;
                border-radius: 0 0 8px 8px;
            }}
            .button {{
                display: inline-block;
                background: #1e40af;
                color: white;
                padding: 12px 24px;
                text-decoration: none;
                border-radius: 6px;
                margin: 20px 0;
            }}
            .info-box {{
                background: #f0f9ff;
                border: 1px solid #bae6fd;
                padding: 15px;
                border-radius: 6px;
                margin: 20px 0;
            }}
            .contact-info {{
                background: #f9fafb;
                padding: 15px;
                border-radius: 6px;
                margin: 20px 0;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Shenzhen Lianjin Optoelectronics</h1>
            <p>Leading LED Display Solutions</p>
        </div>
        
        <div class="content">
            {content_data.get('body_html', content_data.get('body', '').replace('\\n', '<br>'))}
        </div>
        
        <div class="footer">
            <p><strong>Shenzhen Lianjin Optoelectronics Co., Ltd.</strong></p>
            <p>Email: sales@lianjin-led.com | Phone: +86-755-1234-5678</p>
            <p>Address: Shenzhen, Guangdong, China</p>
            <p>&copy; 2024 All rights reserved.</p>
        </div>
    </body>
    </html>
    """
    
    return html_template

def get_inquiry_confirmation_html(inquiry_data):
    """生成询盘确认的HTML邮件"""
    
    body_html = f"""
    <h2>Thank you for your inquiry!</h2>
    <p>Dear {inquiry_data.get('name', 'Valued Customer')},</p>
    
    <p>We have successfully received your inquiry and our team will respond within 24 hours.</p>
    
    <div class="info-box">
        <h3>Inquiry Summary</h3>
        <p><strong>Inquiry Type:</strong> {inquiry_data.get('inquiry_type', 'General').title()}</p>
        <p><strong>Product Interest:</strong> {inquiry_data.get('product_interest', 'General LED Solutions')}</p>
        {f'<p><strong>Budget Range:</strong> {inquiry_data.get("budget_range", "").replace("-", " - ").replace("k", ",000").replace("over-500k", "Over $500,000")}</p>' if inquiry_data.get('budget_range') else ''}
        {f'<p><strong>Screen Size:</strong> {inquiry_data.get("screen_size")}</p>' if inquiry_data.get('screen_size') else ''}
    </div>
    
    <h3>What Happens Next?</h3>
    <ol>
        <li><strong>Review & Analysis:</strong> Our technical team will review your requirements</li>
        <li><strong>Personal Response:</strong> A dedicated sales engineer will contact you within 24 hours</li>
        <li><strong>Custom Proposal:</strong> We'll prepare a detailed proposal with specifications and pricing</li>
    </ol>
    
    <div class="contact-info">
        <h3>Need Immediate Assistance?</h3>
        <p><strong>Email:</strong> <a href="mailto:sales@lianjin-led.com">sales@lianjin-led.com</a></p>
        <p><strong>Phone:</strong> <a href="tel:+8675512345678">+86-755-1234-5678</a></p>
        <p><strong>WhatsApp:</strong> +86 123 456 7890</p>
    </div>
    
    <p>We look forward to working with you on your LED display project!</p>
    
    <p>Best regards,<br>
    <strong>Sales Team</strong><br>
    Shenzhen Lianjin Optoelectronics Co., Ltd.</p>
    """
    
    return {
        'subject': f"Thank you for your inquiry - Reference #{inquiry_data.get('inquiry_id', 'N/A')}",
        'body_html': body_html
    }

def get_admin_notification_html(inquiry_data):
    """生成管理员通知的HTML邮件"""
    
    priority_color = {
        'high': '#dc2626',
        'normal': '#059669',
        'low': '#6b7280'
    }
    
    priority = inquiry_data.get('priority', 'normal')
    
    body_html = f"""
    <h2 style="color: {priority_color.get(priority, '#059669')};">
        New {priority.title()} Priority Inquiry
    </h2>
    
    <div class="info-box">
        <h3>Contact Information</h3>
        <p><strong>Name:</strong> {inquiry_data.get('name', 'N/A')}</p>
        <p><strong>Email:</strong> <a href="mailto:{inquiry_data.get('email', '')}">{inquiry_data.get('email', 'N/A')}</a></p>
        <p><strong>Company:</strong> {inquiry_data.get('company', 'N/A')}</p>
        <p><strong>Phone:</strong> {inquiry_data.get('phone', 'N/A')}</p>
        <p><strong>Country:</strong> {inquiry_data.get('country', 'N/A')}</p>
    </div>
    
    <div class="info-box">
        <h3>Inquiry Details</h3>
        <p><strong>Type:</strong> {inquiry_data.get('inquiry_type', 'General').title()}</p>
        <p><strong>Product Interest:</strong> {inquiry_data.get('product_interest', 'N/A')}</p>
        <p><strong>Screen Size:</strong> {inquiry_data.get('screen_size', 'N/A')}</p>
        <p><strong>Budget Range:</strong> {inquiry_data.get('budget_range', 'N/A')}</p>
        <p><strong>Priority:</strong> <span style="color: {priority_color.get(priority, '#059669')}; font-weight: bold;">{priority.title()}</span></p>
        {f'<p><strong>Estimated Value:</strong> ${inquiry_data.get("estimated_value", "N/A"):,}</p>' if inquiry_data.get('estimated_value') else ''}
    </div>
    
    <div class="info-box">
        <h3>Message</h3>
        <p style="background: #f9fafb; padding: 15px; border-radius: 4px; font-style: italic;">
            "{inquiry_data.get('message', 'No message provided')}"
        </p>
    </div>
    
    <div class="info-box">
        <h3>Additional Information</h3>
        <p><strong>Newsletter:</strong> {'Yes' if inquiry_data.get('newsletter') == '1' else 'No'}</p>
        <p><strong>Language:</strong> {inquiry_data.get('language', 'en').upper()}</p>
        <p><strong>Source:</strong> {inquiry_data.get('source', 'website').title()}</p>
        <p><strong>User Agent:</strong> {inquiry_data.get('user_agent', 'N/A')[:100]}...</p>
        <p><strong>Timestamp:</strong> {inquiry_data.get('timestamp', 'N/A')}</p>
    </div>
    
    <a href="http://localhost:5000/admin/inquiries/{inquiry_data.get('inquiry_id', '')}" class="button">
        View in Admin Panel
    </a>
    
    <p style="color: #dc2626; font-weight: bold;">
        ⚠️ Please respond to this inquiry within 24 hours.
    </p>
    """
    
    return {
        'subject': f"🔔 New {priority.title()} Priority Inquiry from {inquiry_data.get('name', 'Unknown')} - {inquiry_data.get('inquiry_type', 'General').title()}",
        'body_html': body_html
    }

def send_email_notification(to_email, subject, body, from_email="noreply@lianjin-led.com", html_body=None):
    """
    发送邮件通知（增强版本）
    在实际生产环境中，这里应该集成真正的邮件服务
    """
    import smtplib
    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart
    from email.mime.base import MIMEBase
    from email import encoders
    import os
    
    # 开发环境：打印邮件内容
    print(f"📧 EMAIL NOTIFICATION:")
    print(f"To: {to_email}")
    print(f"From: {from_email}")
    print(f"Subject: {subject}")
    print(f"Has HTML: {'Yes' if html_body else 'No'}")
    print("-" * 50)
    
    # 在生产环境中，取消注释以下代码来实际发送邮件
    """
    try:
        # 创建邮件对象
        msg = MIMEMultipart('alternative')
        msg['From'] = from_email
        msg['To'] = to_email
        msg['Subject'] = subject
        
        # 添加纯文本版本
        text_part = MIMEText(body, 'plain', 'utf-8')
        msg.attach(text_part)
        
        # 添加HTML版本（如果提供）
        if html_body:
            html_part = MIMEText(html_body, 'html', 'utf-8')
            msg.attach(html_part)
        
        # SMTP配置（需要根据实际邮件服务器配置）
        smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        smtp_port = int(os.getenv('SMTP_PORT', '587'))
        smtp_username = os.getenv('SMTP_USERNAME', '')
        smtp_password = os.getenv('SMTP_PASSWORD', '')
        
        # 发送邮件
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.send_message(msg)
        
        print(f"✅ Email sent successfully to {to_email}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email to {to_email}: {str(e)}")
        return False
    """
    
    # 开发环境：假设发送成功
    return True

def send_inquiry_notifications(inquiry_data, inquiry_id=None):
    """发送询盘相关的所有通知邮件"""
    
    if inquiry_id:
        inquiry_data['inquiry_id'] = inquiry_id
    
    notifications_sent = []
    
    try:
        # 发送客户确认邮件
        customer_email_data = get_inquiry_confirmation_html(inquiry_data)
        customer_html = get_html_email_template(customer_email_data, 'inquiry_confirmation')
        
        customer_success = send_email_notification(
            to_email=inquiry_data.get('email'),
            subject=customer_email_data['subject'],
            body=f"Thank you for your inquiry! We will respond within 24 hours.",
            html_body=customer_html
        )
        
        if customer_success:
            notifications_sent.append('customer_confirmation')
        
        # 发送管理员通知邮件
        admin_email_data = get_admin_notification_html(inquiry_data)
        admin_html = get_html_email_template(admin_email_data, 'admin_notification')
        
        admin_emails = [
            'sales@lianjin-led.com',
            'admin@lianjin-led.com'  # 可以配置多个管理员邮箱
        ]
        
        for admin_email in admin_emails:
            admin_success = send_email_notification(
                to_email=admin_email,
                subject=admin_email_data['subject'],
                body=f"New inquiry from {inquiry_data.get('name', 'Unknown')}",
                html_body=admin_html
            )
            
            if admin_success:
                notifications_sent.append(f'admin_notification_{admin_email}')
        
        return {
            'success': True,
            'notifications_sent': notifications_sent,
            'total_sent': len(notifications_sent)
        }
        
    except Exception as e:
        print(f"Error sending inquiry notifications: {str(e)}")
        return {
            'success': False,
            'error': str(e),
            'notifications_sent': notifications_sent
        }